In [2]:
import torch

# Scalar

In [3]:
scalar1 = torch.tensor([1.])

In [4]:
print(scalar1)

tensor([1.])


In [5]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


In [7]:
add_scalar = scalar1 + scalar2
sub_scalar = scalar1 - scalar2
mul_scalar = scalar1 * scalar2
div_scalar = scalar1 / scalar2
print(add_scalar, sub_scalar, mul_scalar, div_scalar)

tensor([4.]) tensor([-2.]) tensor([3.]) tensor([0.3333])


In [8]:
torch.add(scalar1, scalar2)
torch.sub(scalar1, scalar2)
torch.mul(scalar1, scalar2)
torch.div(scalar1, scalar2)

tensor([0.3333])

# Vector

In [9]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [10]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [15]:
torch.dot(vector1, vector2) # 벡터 내적 계산

tensor(32.)

# Matrix

In [16]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [19]:
# 행렬의 곱
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

# Tensor

In [21]:
tensor1 = torch.tensor([[[1., 2.], [3.,4.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]]])


In [22]:
tensor2 = torch.tensor([[[5., 6.], [7.,8.]]])
print(tensor2)

tensor([[[5., 6.],
         [7., 8.]]])


In [23]:
torch.matmul(tensor1, tensor2)

tensor([[[19., 22.],
         [43., 50.]]])

# Autograd

In [25]:
import torch
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

In [26]:
print(DEVICE)

cuda


In [27]:
BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

In [29]:
x = torch.randn(BATCH_SIZE, INPUT_SIZE, device = DEVICE, dtype = torch.float, requires_grad = False)
y = torch.randn(BATCH_SIZE, OUTPUT_SIZE, device = DEVICE, dtype = torch.float, requires_grad = False)
w1 = torch.randn(INPUT_SIZE, HIDDEN_SIZE, device = DEVICE, dtype = torch.float, requires_grad = True)
w2 = torch.randn(HIDDEN_SIZE, OUTPUT_SIZE, device = DEVICE, dtype = torch.float, requires_grad = True)

In [31]:
learning_rate = 1e-6
for t in range(1, 501):
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 0:
        print("Iteration: ", t, "\t", "Loss: ", loss.item())
    loss.backward()
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w1.grad.zero_()
        w2.grad.zero_()

Iteration:  100 	 Loss:  239.2540283203125
Iteration:  200 	 Loss:  0.456472247838974
Iteration:  300 	 Loss:  0.0020911425817757845
Iteration:  400 	 Loss:  9.306118590757251e-05
Iteration:  500 	 Loss:  2.3576532839797437e-05
